build: off

install:
  - git submodule update --init
  - cinst jdk8 -params 'installdir=C:\\jdk8'
  - SET JAVA_HOME=C:\jdk8
  - SET PATH=C:\jdk8\bin;%PATH%
  - curl -fsS -L -o jre.zip https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.161-1/java-1.8.0-openjdk-1.8.0.161-1.b14.ojdkbuild.windows.x86_64.zip
  - 7z x jre.zip -aoa
  - move java-1.8.0-openjdk-1.8.0.161-1.b14.ojdkbuild.windows.x86_64\jre .
  - curl -fsS -L -o jfx.zip https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.171-1/openjfx-8.0.171-1.b11.ojdkbuild.windows.x86_64.zip
  - 7z x jfx.zip -aoa
  - xcopy openjfx-8.0.171-1.b11.ojdkbuild.windows.x86_64\jre jre  /s /y

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\jdk8 -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean check test build fatJar createExe
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" windows.nsi'

artifacts:
  - path: dist\vertretungsplan-uploader.exe
    name: Installer

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: lOprJR3QLQx5gPp3LUyctRw0v7KIpgIlpw2Wd/esxAhv9t6Nm/8roM9LGN71mnw1
  artifact: dist\vertretungsplan-uploader.exe
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true